### ISSUE TITLE
Missing package: cryptography

### ISSUE THREAD

**Issue by mdraws-kpm** [piwheels/packages#329] opened 2022-10-05 21:02 UTC
### Package name

cryptography

### Package version

38.0.0, 38.0.1

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [x] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

rust compiler error again. 
`error: Rust 1.41.1 does not match extension requirement >=1.48.0`

**Comment by mdraws-kpm** [comment] 2022-10-05 22:03
I got it to successfully build version `38.0.1` on a `pi 3B+` running `buster`. 
I used rustup to install the rust compiler version `1.64.0`
I also needed `libssl-dev` although I suspect you guys already have that on there.

**Comment by bennuttall** [comment] 2022-10-05 22:06
Pending https://github.com/piwheels/piwheels/pull/322

**Comment by mdraws-kpm** [comment] 2022-10-05 22:08
Ok great thanks, we can close this if you want, or leave it open so others know about the PR.

**Comment by jedie** [comment] 2022-11-13 20:23
v38.0.3 is missing, because the build failed:

![grafik](https://user-images.githubusercontent.com/71315/201542253-d1f309ad-4fae-4711-aec1-b211413a96bb.png)

https://www.piwheels.org/logs/0000/0895/0427.txt

**Comment by gloriousDan** [comment] 2022-11-13 22:30
I think once https://github.com/piwheels/piwheels/pull/328 is merged it should be fixed.

**Comment by mdraws-kpm** [comment] 2023-01-13 15:35
Any update on this, we just need to bump the rust version for it to compile. It's a pain to have to keep doing it myself as it takes a long time.

**Comment by Stefal** [comment] 2023-02-13 14:24
If you're interested, I've build some cryptography wheels for python 3.7 : 
https://github.com/Stefal/rtkbase/tree/dev/tools/wheel

**Comment by mdsketch** [comment] 2023-02-13 14:35
If the issue is someone is needed to maintain the build pipeline for this package on piwheel, I'd be more than happy to help out. 

It would make my life so much easier if this was kept up to date with the rapid release schedule of cryptography package.

**Comment by bennuttall** [comment] 2023-02-21 19:32
All recent builds now available

**Closed by bennuttall** 2023-02-21 19:32 UTC
Labels: missing package, requires rust
