### ISSUE TITLE
Problem with package: cryptography - can't find Rust compiler

### ISSUE THREAD

**Issue by steersbob** [piwheels/packages#369] opened 2023-06-19 11:33 UTC
### Package name

cryptography

### Package version

`>= 40.0.2`

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

The build for both Python 3.7 and 3.9 fails due to `rustc` being unavailable.

Relevant section of build logs:

```
2023-06-01T12:55:20,163   running build_rust

2023-06-01T12:55:20,198       =============================DEBUG ASSISTANCE=============================
2023-06-01T12:55:20,198       If you are seeing a compilation error please try the following steps to
2023-06-01T12:55:20,198       successfully install cryptography:
2023-06-01T12:55:20,198       1) Upgrade to the latest pip and try again. This will fix errors for most
2023-06-01T12:55:20,199          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
2023-06-01T12:55:20,199       2) Read https://cryptography.io/en/latest/installation/ for specific
2023-06-01T12:55:20,199          instructions for your platform.
2023-06-01T12:55:20,199       3) Check our frequently asked questions for more information:
2023-06-01T12:55:20,199          https://cryptography.io/en/latest/faq/
2023-06-01T12:55:20,199       4) Ensure you have a recent Rust toolchain installed:
2023-06-01T12:55:20,199          https://cryptography.io/en/latest/installation/#rust

2023-06-01T12:55:20,200       Python: 3.9.2
2023-06-01T12:55:20,200       platform: Linux-6.1.21-v7l+-armv7l-with-glibc2.31
2023-06-01T12:55:20,200       pip: n/a
2023-06-01T12:55:20,200       setuptools: 67.8.0
2023-06-01T12:55:20,200       setuptools_rust: 1.6.0
2023-06-01T12:55:20,200       rustc: n/a
2023-06-01T12:55:20,200       =============================DEBUG ASSISTANCE=============================

2023-06-01T12:55:20,201   error: can't find Rust compiler

2023-06-01T12:55:20,201   If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

2023-06-01T12:55:20,201   To update pip, run:

2023-06-01T12:55:20,201       pip install --upgrade pip

2023-06-01T12:55:20,202   and then retry package installation.

2023-06-01T12:55:20,202   If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

2023-06-01T12:55:20,202   This package requires Rust >=1.56.0.
2023-06-01T12:55:20,313   ERROR: [present-rich] Building wheel for cryptography (pyproject.toml) exited with 1
2023-06-01T12:55:20,334   [bold magenta]full command[/]: [blue]/usr/bin/python3 /home/piwheels/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmph65rrcq5[/]
2023-06-01T12:55:20,334   [bold magenta]cwd[/]: /tmp/pip-wheel-mpqgjee1/cryptography_289cd24f45e041ac9042d4b3bd5750de
2023-06-01T12:55:20,334   Building wheel for cryptography (pyproject.toml): finished with status 'error'
2023-06-01T12:55:20,336   ERROR: Failed building wheel for cryptography
2023-06-01T12:55:20,339 Failed to build cryptography
```

**Comment by bennuttall** [comment] 2023-06-28 20:05
Duplicate of #359 - we've had some issues with rust builds - working on it

**Closed by bennuttall** 2023-06-28 20:05 UTC
Labels: package issue
