### ISSUE TITLE
Missing package: opencv-python-headless

### ISSUE THREAD

**Issue by bernardolansing** [piwheels/packages#421] opened 2024-01-14 13:20 UTC
### Package name

opencv-python-headless

### Package version

4.9.0.80

### PyPI URL

https://pypi.org/project/opencv-python-headless/

### piwheels URL

https://www.piwheels.org/project/opencv-python-headless/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

I've noticed that there are not wheels available for this package on piwheels. So I've just built them myself, took like 10 hours or so. Is there a way I can share my build with you so future installations will be faster? Please explain carefully as I am not that experienced in this subject.

**Comment by bennuttall** [comment] 2024-01-14 22:07
Duplicate of https://github.com/piwheels/packages/issues/350

> I've noticed that there are not wheels available for this package on piwheels. So I've just built them myself, took like 10 hours or so. Is there a way I can share my build with you so future installations will be faster? Please explain carefully as I am not that experienced in this subject.

I had issues building them due to issues with cmake. Which version of cmake do you have?

**Closed by bennuttall** 2024-01-14 22:07 UTC
Labels: missing package

**Comment by bernardolansing** [comment] 2024-02-02 20:58
Any updates? We still don't have the wheels available on piwheels. I'd be happy to help if I can.

P.S.: forgot to mention that I am on a armv7l (32bits) arch.
