### ISSUE TITLE
Error installing opencv-contrib-python-headless

### ISSUE THREAD

**Issue by gjcopperwheat** [piwheels/packages#37] opened 2019-07-26 19:32 UTC
Package name: opencv-contrib-python-headless
Issue type: Broken Package - Install Failure
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/opencv-contrib-python-headless/
Version: 4.1.0.25
Python version: 3.7.3
More information:
- Raspbian ver 10 (Buster)
- Raspberry Pi 3 Model B Rev 1.2
- pip 19.2.1 (python 3.7)

```
sudo pip install opencv-contrib-python-headless==4.1.0.25
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-contrib-python-headless==4.1.0.25
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python-headless==4.1.0.25 (from versions: none)
ERROR: No matching distribution found for opencv-contrib-python-headless==4.1.0.25
```
Usual update and upgrade happened before.

Probably expect this to be my D’oh moment.

Thanks.

**Comment by bennuttall** [comment] 2019-08-01 12:53
Duplicate of #32

**Closed by bennuttall** 2019-08-01 12:53 UTC
