### ISSUE TITLE
Missing package: cryptography

### ISSUE THREAD

**Issue by ronbuist** [piwheels/packages#334] opened 2022-11-11 07:52 UTC
### Package name

cryptography

### Package version

38.0.3

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Error message indicates Rust compiler is missing. This did not seem to be the case for version 38.0.2 (yanked).

**Comment by bennuttall** [comment] 2022-11-11 10:08
Duplicate of #333 and #329 - see https://github.com/piwheels/piwheels/pull/322

**Closed by bennuttall** 2022-11-11 10:08 UTC
Labels: missing package
