### ISSUE TITLE
Missing package: cryptography - Request to be maintainer

### ISSUE THREAD

**Issue by mdsketch** [piwheels/packages#375] opened 2023-07-07 15:08 UTC
### Package name

cryptography

### Package version

40.0.2, 41.x.x

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

I would like to become the maintainer for this Package. I have to continuously build this manually and update my local CI pipeline to fix, have been for over a year.

Please let me know if there is any way I can help out with this.

Thank you.

**Comment by bennuttall** [comment] 2023-07-07 16:02
Duplicate of #359. This was being handled in https://github.com/piwheels/piwheels/pull/328 but we didn't seem to get it over the line.

@MichaIng did you get anywhere with it? I'm more stable, accommodation and internet connection wise, than before.

**Closed by bennuttall** 2023-07-07 16:02 UTC
Labels: missing package

**Comment by MichaIng** [comment] 2023-07-07 16:18
@bennuttall 
Did you read my last email from 2023-05-20? I tested [my branch](https://github.com/MichaIng/piwheels/tree/patch-1) on a Buster slave with some adjustments to print more debug info and compile `bcrypt` and `cryptography` without any piwheels master communication. I just checked and the slave is still up with console log. Probably you find time to retest on another Buster slave whether it does not work for you as expected as well?

**Comment by MichaIng** [comment] 2023-09-14 17:46
The issue has been solved in the meantime, recent cryptography builds and other modules with Rust code embedded are available on piwheels now: https://piwheels.org/project/cryptography/

@bennuttall 
I just see for those new builds which are done for Bookworm as well (awesome), the project page contains only a Bookworm column (but all Python 3.7 and 3.9 wheels are there as well) and no success indicator icon anymore.

**Comment by bennuttall** [comment] 2023-09-14 17:55
It's because the table only shows active ABIs and we're currently working on the 3.11 backlog. See the banner at the top of the page on piwheels.org

**Comment by MichaIng** [comment] 2023-09-14 17:56
Ah lol, I even missed he banner, sorry for the noise 🙂.
