### ISSUE TITLE
Problem with package: pyproj

### ISSUE THREAD

**Issue by capoaira** [piwheels/packages#346] opened 2023-03-10 08:57 UTC
### Package name

pyproj

### Package version

all

### PyPI URL

https://pypi.org/project/pyproj/

### piwheels URL

https://www.piwheels.org/project/pyproj/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Unfortunately, all builds are failed and I cannot install it on my raspy. I need it as dependency for another package.
On Windows, the installation works.

**Comment by bennuttall** [comment] 2023-03-10 21:04
Duplicate of #60

**Closed by bennuttall** 2023-03-10 21:04 UTC
Labels: package issue
