### ISSUE TITLE
Missing package: cryptography for version 43.0.1

### ISSUE THREAD

**Issue by yakirm-cr** [piwheels/packages#469] opened 2024-09-04 02:42 UTC
### Package name

cryptography

### Package version

43.0.1

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

**Comment by orosam** [comment] 2024-09-04 13:48
According to the build logs for [bullseye](https://www.piwheels.org/logs/0000/1236/6025.txt) and [bookworm](https://www.piwheels.org/logs/0000/1236/5719.txt):

* Both resulted in `cryptography-43.0.1-cp37-abi3-linux_armv7l.whl`
* The bullseye version finished later.

It looks like as if the bullsey version overwrote the bookworm version. However, there really should be two files, if I understand correctly, since the bullseye version is linked against openssl1.1, while the bookworm version is against openssl3.

**Comment by bennuttall** [comment] 2024-09-04 13:57
Duplicate of #464 - not an easy fix due to the wheels starting to be tagged as `abi3` so we can't build separate versions for Bullseye and Bookworm. Please pin the previous version.

**Closed by bennuttall** 2024-09-04 13:57 UTC
Labels: missing package

**Comment by orosam** [comment] 2024-09-04 14:01
Wouldn't it be possible to override the platform compatibility tag in the bullseye build to e.g. `cp311-abi3-linux_armv7l`? 

While it's pretty much a hack, it might solve most issues due to bookworm having python3.11, so theoretically pip should choose the `cp11-abi3-linux_armv7l` tag over `cp37-abi3-linux_armv7l`.
