### ISSUE TITLE
Missing package: pyobject

### ISSUE THREAD

**Issue by ukBaz** [piwheels/packages#339] opened 2022-12-17 11:58 UTC
### Package name

pyobject

### Package version

all

### PyPI URL

https://pypi.org/project/pyobject/

### piwheels URL

https://www.piwheels.org/project/pyobject/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

I got the package to build with the following commands:

```None
$ python3 -m venv venv
$ . venv/bin/activate
(venv) $ pip install pip --upgrade
[...]
(venv) $ python -c "from gi.repository import GLib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
(venv) $ sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
(venv) $ pip install PyGObject
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyGObject
  Using cached PyGObject-3.42.2.tar.gz (719 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycairo>=1.16.0
  Using cached https://www.piwheels.org/simple/pycairo/pycairo-1.23.0-cp39-cp39-linux_armv7l.whl (296 kB)
Building wheels for collected packages: PyGObject
  Building wheel for PyGObject (pyproject.toml) ... done
  Created wheel for PyGObject: filename=PyGObject-3.42.2-cp39-cp39-linux_armv7l.whl size=728411 sha256=e7799aa695a6d7d61251a467b4923fb60d4a991045a1d5032100b2c813284aa9
  Stored in directory: /home/pi/.cache/pip/wheels/c4/2e/6f/761793b8a4705cc4495bf6db1e1ac174526a5e30f272633855
Successfully built PyGObject
Installing collected packages: pycairo, PyGObject
Successfully installed PyGObject-3.42.2 pycairo-1.23.0
(venv) $ python -c "from gi.repository import GLib"
(venv) $ 
```

The key piece in this seems to be the list of packages required which is:
```None
sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
```

**Comment by bennuttall** [comment] 2023-02-22 09:50
Looks like you meant PyGobject - I've installed the requirements for that and it's now in the build queue.

Duplicate of #336

**Closed by bennuttall** 2023-02-22 09:50 UTC
Labels: missing package

**Comment by ukBaz** [comment] 2023-02-22 11:54
Yes, it looks like I did mean [PyGObject](https://pypi.org/project/PyGObject/)  Damn that case sensitivity :-(

Thank you.
