### ISSUE TITLE
Missing package: opencv-python-headless

### ISSUE THREAD

**Issue by oberluz** [piwheels/packages#368] opened 2023-06-06 11:16 UTC
### Package name

opencv-python-headless

### Package version

4.7.0.72

### PyPI URL

https://pypi.org/project/opencv-python-headless/

### piwheels URL

https://www.piwheels.org/project/opencv-python-headless/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Seems the build machine  ran out of memory (see https://www.piwheels.org/logs/0000/0936/6310.txt)

```
2023-02-23T00:44:08,844   virtual memory exhausted: Cannot allocate memory
2023-02-23T00:44:08,844   ninja: build stopped: subcommand failed.
2023-02-23T00:44:08,849   Traceback (most recent call last):
2023-02-23T00:44:08,853     File "/tmp/pip-build-env-yylyfs0s/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 642, in setup
2023-02-23T00:44:08,853       cmkr.make(make_args, install_target=cmake_install_target, env=env)
2023-02-23T00:44:08,853     File "/tmp/pip-build-env-yylyfs0s/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 679, in make
2023-02-23T00:44:08,853       self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
2023-02-23T00:44:08,854     File "/tmp/pip-build-env-yylyfs0s/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 710, in make_impl
2023-02-23T00:44:08,854       raise SKBuildError(

2023-02-23T00:44:08,855   An error occurred while building with CMake.
2023-02-23T00:44:08,856     Command:
2023-02-23T00:44:08,856       /tmp/pip-build-env-yylyfs0s/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
2023-02-23T00:44:08,856     Install target:
2023-02-23T00:44:08,856       install
```

**Comment by bennuttall** [comment] 2023-11-04 17:58
Working on this but it's a duplicate of #350

**Closed by bennuttall** 2023-11-04 17:58 UTC
Labels: missing package
