### ISSUE TITLE
Missing package: pytorch 1.6.0

### ISSUE THREAD

**Issue by suhridh** [piwheels/packages#161] opened 2020-09-14 20:42 UTC
Package name: pytorch
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/torch/
Link to piwheels page: https://www.piwheels.org/project/pytorch/
Version: 1.6.0
Python version: 3.7
I am the maintainer: No
More information: Request you to make it publicly available as I could not find the right person to contact for this. Here's the link for it - [pytorch-1.6.0-linuxv7l.whl](https://drive.google.com/file/d/1U9xwHsECjatOkQASQza9I8muQmOUAF9G/view?usp=sharing)

**Comment by suhridh** [comment] 2020-09-14 20:45
Apologies, small edit - piwheels page should be https://www.piwheels.org/project/torch/

**Comment by bennuttall** [comment] 2020-09-14 21:52
Duplicate of #2 - long standing issue but not automatable as they don't provide source distribution on PyPI.

We don't upload wheels produced by third party - all we can do is look at build instructions and consider building it ourselves if we're sure it's ok to do so. Please add further comments to #2.

**Closed by bennuttall** 2020-09-14 21:52 UTC
