### ISSUE TITLE
Missing package: cryptography

### ISSUE THREAD

**Issue by gloriousDan** [piwheels/packages#333] opened 2022-11-09 16:54 UTC
### Package name

cryptography

### Package version

38.0.3

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

The build log complains about missing rustc. 
I'm not sure why it worked for previous versions and not for 38.0.3 anymore.

This is the error message:
```
2022-11-01T22:17:12,363   running build_rust

2022-11-01T22:17:12,410       =============================DEBUG ASSISTANCE=============================
2022-11-01T22:17:12,410       If you are seeing a compilation error please try the following steps to
2022-11-01T22:17:12,410       successfully install cryptography:
2022-11-01T22:17:12,410       1) Upgrade to the latest pip and try again. This will fix errors for most
2022-11-01T22:17:12,411          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
2022-11-01T22:17:12,411       2) Read https://cryptography.io/en/latest/installation/ for specific
2022-11-01T22:17:12,411          instructions for your platform.
2022-11-01T22:17:12,411       3) Check our frequently asked questions for more information:
2022-11-01T22:17:12,411          https://cryptography.io/en/latest/faq/
2022-11-01T22:17:12,411       4) Ensure you have a recent Rust toolchain installed:
2022-11-01T22:17:12,411          https://cryptography.io/en/latest/installation/#rust

2022-11-01T22:17:12,412       Python: 3.9.2
2022-11-01T22:17:12,412       platform: Linux-5.15.61-v7l+-armv7l-with-glibc2.31
2022-11-01T22:17:12,412       pip: n/a
2022-11-01T22:17:12,412       setuptools: 65.5.0
2022-11-01T22:17:12,412       setuptools_rust: 1.5.2
2022-11-01T22:17:12,412       rustc: n/a
2022-11-01T22:17:12,412       =============================DEBUG ASSISTANCE=============================

2022-11-01T22:17:12,413   error: can't find Rust compiler

2022-11-01T22:17:12,413   If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

2022-11-01T22:17:12,413   To update pip, run:

2022-11-01T22:17:12,413       pip install --upgrade pip

2022-11-01T22:17:12,414   and then retry package installation.

2022-11-01T22:17:12,414   If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

2022-11-01T22:17:12,414   This package requires Rust >=1.48.0.
2022-11-01T22:17:12,658   ERROR: [present-rich] Building wheel for cryptography (pyproject.toml) exited with 1
2022-11-01T22:17:12,676   [bold magenta]full command[/]: [blue]/usr/bin/python3 /usr/local/lib/python3.9/dist-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpdsh_3t89[/]
2022-11-01T22:17:12,676   [bold magenta]cwd[/]: /tmp/pip-wheel-fa0fa6wo/cryptography_5cf0b90370f64cba93e6fdc5f7a57a9c
2022-11-01T22:17:12,677   Building wheel for cryptography (pyproject.toml): finished with status 'error'
2022-11-01T22:17:12,679   ERROR: Failed building wheel for cryptography
2022-11-01T22:17:12,682 Failed to build cryptography
2022-11-01T22:17:12,683 ERROR: Failed to build one or more wheels
2022-11-01T22:17:12,684 Exception information:
2022-11-01T22:17:12,684 Traceback (most recent call last):
2022-11-01T22:17:12,684   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
2022-11-01T22:17:12,684     status = run_func(*args)
2022-11-01T22:17:12,684   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
2022-11-01T22:17:12,684     return func(self, options, args)
2022-11-01T22:17:12,684   File "/usr/local/lib/python3.9/dist-packages/pip/_internal/commands/wheel.py", line 201, in run
2022-11-01T22:17:12,684     raise CommandError("Failed to build one or more wheels")
2022-11-01T22:17:12,684 pip._internal.exceptions.CommandError: Failed to build one or more wheels
2022-11-01T22:17:12,686 Removed build tracker: '/tmp/pip-build-tracker-ossng8kk'
```

**Comment by bennuttall** [comment] 2022-11-09 17:22
Duplicate of #329 - see discussions at https://github.com/piwheels/piwheels/pull/322

**Closed by bennuttall** 2022-11-09 17:22 UTC
Labels: missing package

**Comment by gloriousDan** [comment] 2022-11-09 17:28
I saw this and thought that this is not a duplicate of #329 since this issue is about 38.0.3 and the other issue about 38.0.1 and 38.0.0. And since PR https://github.com/piwheels/piwheels/pull/322 is merged shouldn't this issue be resolved?

**Comment by gloriousDan** [comment] 2022-11-09 17:32
Ok sorry, I didn't read the whole conversation before and thought that the issue of rust not being found was resolved.
