### ISSUE TITLE
Missing package: opencv-contrib-python

### ISSUE THREAD

**Issue by JavadRah** [piwheels/packages#45] opened 2019-08-09 18:00 UTC
Package name: opencv-contrib-python
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/opencv-contrib-python/
Link to piwheels page: https://www.piwheels.org/project/opencv-contrib-python/
Version: 4.1.0.25
Python version: 3.7
More information:

**Comment by bennuttall** [comment] 2019-08-09 23:17
Yet another duplicate of pinned issue #28

**Closed by bennuttall** 2019-08-09 23:17 UTC
