### ISSUE TITLE
Missing package: opencv-contrib-python-headless

### ISSUE THREAD

**Issue by doobran** [piwheels/packages#165] opened 2020-10-14 21:16 UTC
Package name: opencv-contrib-python-headless
Issue type: ImportError - undefined symbol
Link to piwheels page: https://www.piwheels.org/project/opencv-contrib-python-headless/#install
Version: all
Python version: 3.7
I am the maintainer: No
More information:
ImportError: /home/pi/.local/lib/python3.7/site-packages/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8

Please use code blocks where appropriate:

```bash
python3
import cv2
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: /home/pi/.local/lib/python3.7/site-packages/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8

```

**Comment by bennuttall** [comment] 2020-10-14 21:47
This is a duplicate of #59 - you'll find the workaround there.

Newer versions of the [other opencv packages](https://blog.piwheels.org/new-opencv-builds-including-opencv-4-4-x/) are available now but the contrib ones are not uploaded to PyPI so we don't have those. You might want to install **opencv-python-headless** instead if you don't specifically need contrib.

**Closed by bennuttall** 2020-10-14 21:47 UTC
