### ISSUE TITLE
Problem with package: cryptography

### ISSUE THREAD

**Issue by yakirm-cr** [piwheels/packages#461] opened 2024-07-23 05:42 UTC
### Package name

cryptography

### Package version

43.0.0

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [ ] Python 3.7
- [ ] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [ ] Yes

### More information

According to the instructions in [piwheels](https://piwheels.org/project/cryptography), `libssl1.1` should be installed.
`libssl1.1` is related to OpenSSL version 1.1, which is replaced by OpenSSL 3 in Raspberry Pi OS 12 (based on Debian 12).
Is it really required on Raspberry Pi OS 12 (with Python 3.11)?
If not, I believe that the installation instructions should be updated for Python 3.11, unless I am missing something...

![image](https://github.com/user-attachments/assets/1309ad36-7e45-42fe-a51b-512e60083815)

**Comment by bennuttall** [comment] 2024-07-23 11:05
Duplicate of #459

**Closed by bennuttall** 2024-07-23 11:05 UTC
Labels: package issue

**Comment by bennuttall** [comment] 2024-07-23 12:03
Ok I see the confusion here.

Your issue referred specifically to cryptography version 43.0.0 on Python 3.11. We don't (currently) have that version built, and there's another issue regarding fixing that build.

> According to the instructions in [piwheels](https://piwheels.org/project/cryptography), libssl1.1 should be installed.

What you are observing is that those instructions don't make sense if you're on Bookworm - and you're right.

If you open up the files for the previous version:

![Screenshot from 2024-07-23 12-56-10](https://github.com/user-attachments/assets/e128e6b7-ae03-45e0-98c0-96dea190004c)

and click "How to install this version" on one of the cp311 wheels, you'll see:

![Screenshot from 2024-07-23 12-56-32](https://github.com/user-attachments/assets/300ed8b6-a8e0-46d3-9c62-7f58c0f496f5)

Unfortunately this is a side-effect of the logic for what we show in that box. By default, we show the instructions for the latest successful build - which in this case is 43.0.0 on Bullseye. If you specifically choose a file, it'll show you the right instructions - which apparently don't require installing openssl at all - presumably it's installed by default.

So once the missing build is completed and succeeds - it *should* go back to the right instructions for cp311.

BUT ... I have a feeling it could still be wrong as our ordering of ABIs is flawed due to being sorted alphabetically (which broke when we reached double digit Python minor versions). See https://github.com/piwheels/piwheels/issues/288

**Comment by bennuttall** [comment] 2024-07-23 16:12
It's built now and despite the ABI ordering issue, it's showing the right info here:

![Screenshot from 2024-07-23 17-11-47](https://github.com/user-attachments/assets/1094b5a5-244d-47ab-9f47-db53fd13d2ad)
