### ISSUE TITLE
Missing package: cryptography

### ISSUE THREAD

**Issue by tropxy** [piwheels/packages#343] opened 2023-02-02 18:48 UTC
### Package name

cryptography

### Package version

39.0.0

### PyPI URL

https://pypi.org/project/cryptography/

### piwheels URL

https://www.piwheels.org/project/cryptography/

### Python version

- [X] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Hi, seems those packages are not available. However, I have generated the binaries for them, including for python 3.10 and 3.11 for both buster and bullseye distros. what would be the procedure to provide those binaries?

**Comment by bennuttall** [comment] 2023-02-03 10:26
Duplicate of #329

**Closed by bennuttall** 2023-02-03 10:26 UTC
Labels: missing package
