### ISSUE TITLE
unicorn wheel not supported on Pi0W

### ISSUE THREAD

**Issue by MysteryBlokHed** [piwheels/packages#223] opened 2021-07-14 22:03 UTC
Package name: unicorn
Link to PyPI page: <https://pypi.org/project/unicorn/>
Link to piwheels page: <https://www.piwheels.org/project/unicorn/>
Version: 1.0.3
Python version: 3.7.3
I am the maintainer: No
More information:

While trying to install [pwntools](https://pypi.org/project/pwntools/) on my Pi0W, I noticed that there wasn't a wheel being downloaded for unicorn, despite one being available.

```
$ pip3 install pwntools
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pwntools
  Downloading https://files.pythonhosted.org/packages/d6/a2/6421a1a74b94a8e7e28e291946606f8f7e6ac68be369b3fe7650b184bc35/pwntools-4.6.0-py2.py3-none-any.whl (10.0MB)
    100% |████████████████████████████████| 10.0MB 1.6MB/s
Requirement already satisfied: pip>=6.0.8 in /usr/lib/python3/dist-packages (from pwntools) (18.1)
Collecting unicorn<1.0.2rc4,>=1.0.2rc1 (from pwntools)
  Downloading https://files.pythonhosted.org/packages/6c/c0/7d9870c4ec6f186096d2d5807d278aad8f097cc9b40968f7626031ad3f1f/unicorn-1.0.2rc3.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 1.6MB/s
```

You can see other wheels being downloaded from piwheels, it just seems to be unicorn:

<details>
    <summary>All collected packages (Click to expand)</summary>

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pwntools
  Downloading https://files.pythonhosted.org/packages/d6/a2/6421a1a74b94a8e7e28e291946606f8f7e6ac68be369b3fe7650b184bc35/pwntools-4.6.0-py2.py3-none-any.whl (10.0MB)
    100% |████████████████████████████████| 10.0MB 1.6MB/s
Requirement already satisfied: pip>=6.0.8 in /usr/lib/python3/dist-packages (from pwntools) (18.1)
Collecting unicorn<1.0.2rc4,>=1.0.2rc1 (from pwntools)
  Downloading https://files.pythonhosted.org/packages/6c/c0/7d9870c4ec6f186096d2d5807d278aad8f097cc9b40968f7626031ad3f1f/unicorn-1.0.2rc3.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 1.6MB/s
Collecting pygments>=2.0 (from pwntools)
  Downloading https://files.pythonhosted.org/packages/a6/c9/be11fce9810793676017f79ffab3c6cb18575844a6c7b8d4ed92f95de604/Pygments-2.9.0-py3-none-any.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 1.6MB/s
Collecting pyserial>=2.7 (from pwntools)
  Downloading https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl (90kB)
    100% |████████████████████████████████| 92kB 1.6MB/s
Collecting paramiko>=1.15.2 (from pwntools)
  Downloading https://files.pythonhosted.org/packages/95/19/124e9287b43e6ff3ebb9cdea3e5e8e88475a873c05ccdf8b7e20d2c4201e/paramiko-2.7.2-py2.py3-none-any.whl (206kB)
    100% |████████████████████████████████| 215kB 1.6MB/s
Collecting mako>=1.0.0 (from pwntools)
  Downloading https://files.pythonhosted.org/packages/f3/54/dbc07fbb20865d3b78fdb7cf7fa713e2cba4f87f71100074ef2dc9f9d1f7/Mako-1.1.4-py2.py3-none-any.whl (75kB)
    100% |████████████████████████████████| 81kB 1.6MB/s
Collecting packaging (from pwntools)
  Downloading https://files.pythonhosted.org/packages/3c/77/e2362b676dc5008d81be423070dd9577fa03be5da2ba1105811900fda546/packaging-21.0-py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 1.5MB/s
Collecting sortedcontainers (from pwntools)
  Downloading https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from pwntools) (1.12.0)
Collecting colored-traceback (from pwntools)
  Downloading https://www.piwheels.org/simple/colored-traceback/colored_traceback-0.3.0-py3-none-any.whl
Collecting pyelftools>=0.2.4 (from pwntools)
  Downloading https://files.pythonhosted.org/packages/6f/50/3d7729d64bb23393aa4c166af250a6e6f9def40c90bf0e9af3c5ad25b6f7/pyelftools-0.27-py2.py3-none-any.whl (151kB)
    100% |████████████████████████████████| 153kB 794kB/s
Collecting capstone>=3.0.5rc2 (from pwntools)
  Downloading https://files.pythonhosted.org/packages/f2/ae/21dbb3ccc30d5cc9e8cdd8febfbf5d16d93b8c10e595280d2aa4631a0d1f/capstone-4.0.2.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 1.6MB/s
Requirement already satisfied: requests>=2.0 in /usr/lib/python3/dist-packages (from pwntools) (2.21.0)
Collecting intervaltree>=3.0 (from pwntools)
  Downloading https://www.piwheels.org/simple/intervaltree/intervaltree-3.1.0-py2.py3-none-any.whl
Collecting pysocks (from pwntools)
  Downloading https://files.pythonhosted.org/packages/8d/59/b4572118e098ac8e46e399a1dd0f2d85403ce8bbaad9ec79373ed6badaf9/PySocks-1.7.1-py3-none-any.whl
Collecting ropgadget>=5.3 (from pwntools)
  Downloading https://files.pythonhosted.org/packages/6d/1f/48329eec6d947a8aa02ba88b11edd88f7c5c32a8840efcff2444769c6373/ROPGadget-6.6-py3-none-any.whl
Collecting python-dateutil (from pwntools)
  Downloading https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 916kB/s
Collecting psutil>=3.3.0 (from pwntools)
  Downloading https://www.piwheels.org/simple/psutil/psutil-5.8.0-cp37-cp37m-linux_armv6l.whl (296kB)
    100% |████████████████████████████████| 296kB 1.2MB/s
Collecting rpyc (from pwntools)
  Downloading https://files.pythonhosted.org/packages/e8/4c/6d456ae4319190d17e0d4cd8c1ee6b6ba9125f0bde18ef37afdb50867a39/rpyc-5.0.1-py3-none-any.whl (68kB)
    100% |████████████████████████████████| 71kB 1.2MB/s
Collecting bcrypt>=3.1.3 (from paramiko>=1.15.2->pwntools)
  Downloading https://www.piwheels.org/simple/bcrypt/bcrypt-3.2.0-cp37-cp37m-linux_armv6l.whl (57kB)
    100% |████████████████████████████████| 61kB 297kB/s
Collecting pynacl>=1.0.1 (from paramiko>=1.15.2->pwntools)
  Downloading https://www.piwheels.org/simple/pynacl/PyNaCl-1.4.0-cp37-cp37m-linux_armv6l.whl (605kB)
    100% |████████████████████████████████| 614kB 1.6MB/s
Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko>=1.15.2->pwntools) (2.6.1)
Collecting MarkupSafe>=0.9.2 (from mako>=1.0.0->pwntools)
  Downloading https://www.piwheels.org/simple/markupsafe/MarkupSafe-2.0.1-cp37-cp37m-linux_armv6l.whl
Collecting pyparsing>=2.0.2 (from packaging->pwntools)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 666kB/s
Collecting plumbum (from rpyc->pwntools)
  Downloading https://files.pythonhosted.org/packages/6c/fc/6cdaf59a001c707333869b054daf1e0df02978d261f20f8b082afcf189c3/plumbum-1.7.0-py2.py3-none-any.whl (116kB)
    100% |████████████████████████████████| 122kB 686kB/s
Collecting cffi>=1.1 (from bcrypt>=3.1.3->paramiko>=1.15.2->pwntools)
  Downloading https://www.piwheels.org/simple/cffi/cffi-1.14.6-cp37-cp37m-linux_armv6l.whl (346kB)
    100% |████████████████████████████████| 348kB 1.4MB/s
Collecting pycparser (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=1.15.2->pwntools)
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 112kB 653kB/s
```
</details>

I tried manually downloading and installing the wheel, which told me that the wheel was not supported:

```
$ pip3 install unicorn-1.0.3-py2.py3-none-manylinux1_armv7l.whl
unicorn-1.0.3-py2.py3-none-manylinux1_armv7l.whl is not a supported wheel on this platform. 
```

I don't have access to another Pi, so I'm not sure if it's a problem with the wheel or if it just isn't supported on my Pi0W.

**Comment by bennuttall** [comment] 2021-07-14 22:33
Ugh, sorry about that - I can see what's happened there. It's caused by https://github.com/piwheels/piwheels/issues/275 and will be resolved by https://github.com/piwheels/piwheels/pull/276

For now I'll remove that wheel

Thanks for the clear report

**Comment by bennuttall** [comment] 2021-07-14 22:42
Actually, no, I'm wrong. It's an upstream issue. The maintainer has done some very nonstandard stuff in their setup.py. You'll have to report it to the maintainers. They've made it impossible to build a linux_armv6l or linux_armv7l wheel from the source distribution.

**Closed** 2021-07-15 17:14 UTC
Labels: package issue, upstream issue
