### ISSUE TITLE
Hash Mismatch - opencv-contrib-python

### ISSUE THREAD

**Issue by gilnims-ssc** [piwheels/packages#55] opened 2019-10-06 19:35 UTC
_pip3 install opencv-contrib-python_ produces a hash mismatch error. Specifically - 

> ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    opencv-contrib-python from https://www.piwheels.org/simple/opencv-contrib-python/opencv_contrib_python-3.4.3.18-cp37-cp37m-linux_armv6l.whl#sha256=3095eaade88d84d93ae0d35878d877a73561e1192fbf99bde2f1d3c5daf4dda3:
        Expected sha256 3095eaade88d84d93ae0d35878d877a73561e1192fbf99bde2f1d3c5daf4dda3
             Got        52f330a942637ce7e52930f28b3c6591b90b901f30d0a3cc88a3491873813f65

**Comment by bennuttall** [comment] 2019-10-07 10:17
Known issue, duplicate of #53, related to #43 and #28. We're working on it.

**Closed by bennuttall** 2019-10-07 10:17 UTC
