### ISSUE TITLE
opencv-python HASH Mismatch 

### ISSUE THREAD

**Issue by DMCroww** [piwheels/packages#53] opened 2019-09-23 18:25 UTC
Hi,
Got an error about HASHES not matching while trying to install opencv-python.
Searched uncle google and found that I should write about it here.

Thanks for help!

Full error:
```bash
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    opencv-python from https://www.piwheels.org/simple/opencv-python/opencv_python-3.4.3.18-cp37-cp37m-linux_armv6l.whl#sha256=7c7e4108bd2f684bca574cd3c8ac82e8ca722eded52f01b84c30a16bf5d5ed33:
        Expected sha256 7c7e4108bd2f684bca574cd3c8ac82e8ca722eded52f01b84c30a16bf5d5ed33
             Got        83be9a18d0489d57f7b8e66db3c53e807bbefe41ec58e715c6966bf1d4b90433
```

**Comment by bennuttall** [comment] 2019-10-07 10:18
Known issue, duplicate of #52, related to #43 and #28. We're working on it.

**Closed by bennuttall** 2019-10-07 10:18 UTC
