### ISSUE TITLE
opencv-python missing for python 3.7

### ISSUE THREAD

**Issue by yurie-nater** [piwheels/packages#38] opened 2019-07-29 15:09 UTC
Package name: opencv-python
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/opencv-python/
Link to piwheels page: https://www.piwheels.org/project/opencv-python/
Version: 4.1.0.25
Python version: 3.7
More information: 
Unable to get opencv-python with raspberry pi model 4 (i.e. buster)

Please use code blocks where appropriate:
pip3 install opencv-python results in the following error:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-python
  ERROR: Could not find a version that satisfies the requirement opencv-python (from versions: none)
ERROR: No matching distribution found for opencv-python

**Comment by bennuttall** [comment] 2019-08-01 12:52
Duplicate of #28

**Closed by bennuttall** 2019-08-01 12:52 UTC
